"""allow fifa stats to be null

Revision ID: f8b33c4589f6
Revises: 33fde74e2b62
Create Date: 2026-08-23 22:24:09.209955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b33c4589f6'
down_revision: Union[str, Sequence[str], None] = '33fde74e2b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "players",
        "pace",
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.alter_column(
        "players",
        "shooting",
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.alter_column(
        "players",
        "dribbling",
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.alter_column(
        "players",
        "passing",
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.alter_column(
        "players",
        "defending",
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.alter_column(
        "players",
        "physical",
        existing_type=sa.INTEGER(),
        nullable=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'league',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players', 'position',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players', 'physical',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'defending',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'passing',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'dribbling',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'shooting',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'pace',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
